language: python
sudo: false
matrix:
  include:
  - python: '3.7'
    env: DEPS="numpy scipy periodictable numba"
    dist: xenial
install:
  - pip install --upgrade pip setuptools wheel
  - "pip install ${DEPS}"
  - pip install coveralls pytest pytest-cov
  - python setup.py install
script:
  - pytest -v --cov=cse --pyargs cse
